name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install --global @ui5/cli
          npm install

      - name: Build UI5 project
        run: |
          ui5 build --clean-dest --include-task="generateManifestBundle"

      - name: Deploy to SAP BTP Cloud Foundry
        uses: sap-actions/mta-deploy@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          mtaPath: 'mta_archives/*.mtar'
          org: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE }}
          apiEndpoint: ${{ secrets.CF_API_ENDPOINT }}
          mtaOperation: 'deploy'
